### ISSUE TITLE
Some data is no longer available

### ISSUE THREAD

**Issue by cceyda** [AIM3-RUC/YouMakeup#4]
These videos no longer seem to be available on youtube. 
['-77Am71NNaU',
 '-Bsv1P88nkI',
 '-g7k6B4T058',
 '1DXdz4lVjZ0',
 '37_RTu02NLw',
 '4TgjZRdHW2U',
 '5S6xm2FH8B0',
 '5U8Mn2-Y69I',
 '68g5w0dnmlM',
 '6oobHtk4mgY',
 '8BKBLp-MFg0',
 '8Zd0jbw-TzM',
 '8lO7M_ckzLg',
 'AKbhI83GEKY',
 'AXMKTzvusU8',
 'B8GDw2RFxUU',
 'C5i0_UqhINI',
 'DAzoYeICKHg',
 'DtEQX3d_qas',
 'EfZNDi9qJFI',
 'Efy_cXWRDoI',
 'FsOJbIjXL_A',
 'FwpIsziOGOA',
 'LkYP5EP0heI',
 'M2F2wsnEbCo',
 'NVccnkqXdWQ',
 'NexHGYDCKyE',
 'NrQTe2Hn2vM',
 'OuaVY1eaFGU',
 'Pyp0yU3Ap3Y',
 'RRAi5Vmfokg',
 'TFNOuAq6PbE',
 'Tcpva8jvEO0',
 'UJRa30_izqc',
 'UMQJ02QCFWk',
 'VsJENcHFC2U',
 'X4WDjEZgtEE',
 'XcoM8PN2G2o',
 'Y9hA7JpF3hA',
 'YyeAnIvLx18',
 'b7IwuiVDibo',
 'bp2BSJbE79Y',
 'cvq_jPiIjyo',
 'dIUl1-97TYQ',
 'e7eIa4O1usc',
 'erPge6ZOpbI',
 'g5de3akeYAQ',
 'glMktp7PwCg',
 'hisHX167fmo',
 'iNn3lXNShds',
 'jJLYfJPs9Z0',
 'jKkEtY0um3w',
 'kThKHdWYKYc',
 'l0_TPoADrj8',
 'ofaXuhUJ-E8',
 'peF2H8CeUT0',
 'rq0qIsWtXXA',
 'tnE5MJ95VDg',
 'uGAUu4CxOPQ',
 'vTbe7Ambqs0',
 'vUeALXpQEe0',
 'vWG3E2sF1go',
 'vatBewX8ptI',
 'wWGouCtr1As',
 'wuog0GZ4umM',
 'xGVxXWZ5Ijw',
 'y11327D3qZ0',
 'y2GRGm9FQds',
 'ydEZnGRxp_U',
 'z-eht1w0fyc',
 'zfEwvyO9k3Q']

**Comment by WeiyingWang** [comment]
Please sign the License and send it to youmakeupvqa@163.com along with the video id list. We will provide the download link.
